# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - panchapatchi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1b660e7f0de94d8f9cc66929465a8603 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_824ecc110d2b4545b489163a83e16096 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1b660e7f0de94d8f9cc66929465a8603 }}/panchapatchi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'panchapatchi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_242fbc8e48374c63999c7b65c2b2c0fa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1b660e7f0de94d8f9cc66929465a8603 }}/panchapatchi:${{ github.sha }}'